### ISSUE TITLE
email width in outlook 2013 is 510px instead of 600px

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/email-html-generator-issues#10]
[Here an email where it happends.](http://www.vermeulenmailservice.nl/mail/display.php?List=18&N=775)

can you fix this??

**Comment by rolficak** [comment]
Please attach the JSON file too.

**Comment by Mailcamp** [comment]
i tried, but github keeps saying:
Unfortunately, we don’t support that file type.  Bestanden kiezen Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

And yess i zipped the JSON file ofcourse :package:

**Comment by Mailcamp** [comment]
i'll send you the JSON by mail

**Comment by rolficak** [comment]
Here's a test with the HTML. https://litmus.com/checklist/emails/public/ce51516 Everythin is okay with Outlook 2013, maybe on 2013 120dpi, there might be something different. Text is enlarged.

If you change the filetype to json.txt for example, than Github will allow the upload. Unfortunately they ban JSON files for some reason... (and even check the ZIP for it)

**Comment by Mailcamp** [comment]
Ok thanks for the fast reply!
We will check it!
