### ISSUE TITLE
When using multi-column with long text, the text will reorder on desktop version

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/email-html-generator-issues#12]
**My Project ID: 574cfe3729f47ce710132702**

01.
I have a multi-column with left image and right text.
![left-image-right-text](https://cloud.githubusercontent.com/assets/5524183/15662402/d628ac14-2722-11e6-9642-4a13cbfc1ef4.png)

02.
If preview the eDM, the right text will reorder and show below at the left image.
![right-text-reorder](https://cloud.githubusercontent.com/assets/5524183/15662439/45b47d24-2723-11e6-8cf9-c9f2a901e3d8.png)

03.
Then we try to disable the reorder function at the multi-column, the right text still will reorder and show below at the left image.
![disable-reorder](https://cloud.githubusercontent.com/assets/5524183/15662514/07048fa0-2724-11e6-95f4-e0406c9f0365.png)

04.
Also this issue will occur on the web version too.
![web-version](https://cloud.githubusercontent.com/assets/5524183/15662714/05aca6d6-2726-11e6-95ac-a525546ddd3f.png)

Please help to fix it. Thanks!

**Comment by confettidc** [comment]
Anyone can update this issue?

Thanks.

**Comment by gyulanemeth** [comment]
Hello,

having long lines without whitespaces in emails is generally a bad practice, it will break the design in several cases, not this case only. It even can enlarge the width of the email. Please don't use long lines without whitespaces.
