### ISSUE TITLE
Spacing changes in hotmail

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/email-html-generator-issues#17]
Hi,

The spacing in two textfields changed when the newsletter is sended to hotmail.
How can this be fixed?

![screenshot 2](https://cloud.githubusercontent.com/assets/16222817/16615125/b7e9166c-4374-11e6-9189-9c4dbda279d6.png)

[577b826c54ca1cda34bbd165.json (2).txt](https://github.com/EDMdesigner/email-html-generator-issues/files/349552/577b826c54ca1cda34bbd165.json.2.txt)

Thanks in advance

**Comment by ughoo** [comment]
Hi, 

Hotmail/outlook.com is very curios about typography, and has a lots of heuretics like solution to override texts in different cases. The only one difference i saw, is the second textbox contains an BR after the first bolded line. This break can achieve that hotmail rendering could choose a different behavior.... i guess.... Please try to remove that line break and please check the results... let me know if it works! thanks

**Comment by Mailcamp** [comment]
hmmm strange.. the spacing of the first textbox is back to normal when i remove the br from the second text box. But the second textbox is still wrong. when i remove the second textbox the first textbox gets wrong again. have you any idea what to try next?

**Comment by ughoo** [comment]
Try duplicate the good and bad textboxes, check them a few times, try to delete one by one, while still checkin all variations. There is no documented details about how these MS typo manipulations works....somehow it can relates to the number of html tags used in the code but no clue to understand the logic behind.

**Comment by Mailcamp** [comment]
hmmm ok... already tried that before i created this ticket.

**Comment by smiska** [comment]
Hi,

Do you still experience problems related this issue, or have any follow up inquiries or thoughts?
In case you don't have comments during the following week, I will close the issue.
Thanks!

**Comment by RichardMailcamp** [comment]
I think this was my colleague, i'll forward the mail

Richard

**Comment by Silassiai** [comment]
You can close this issue

**Comment by smiska** [comment]
Thanks!
