### ISSUE TITLE
502 Bad Gateway when generate html (top urgent)

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/email-html-generator-issues#20]
Dear Support,

We received "502 Gateway Timeout" page when generate html for **any project**:
![2016-10-01_11-11-39](https://cloud.githubusercontent.com/assets/5524183/19011467/4e0c2958-87c8-11e6-81c0-d1e6c9ea53b7.gif)

As our customer is going to send eDM **today**, please solve this problem as soon as possible.
Please solve it as soon as possible.

Thanks!

**Comment by gyulanemeth** [comment]
Hello, we have fixed it on Saturday morning. Sorry that it happened.
