### ISSUE TITLE
Mail content align left problem in Android native mail client

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/email-html-generator-issues#22]
Dear Support,

Project ID: 584619c8c7d5f2584ed90f5c

We discovered the whole mail content will keep align left when view in native mail client in Samsung Galaxy Note5:

![default](https://cloud.githubusercontent.com/assets/5524183/20915300/05ade7f6-bbc0-11e6-8d49-a8bf402eaf20.png)

Can this be solved or can the fullwidth element can set width greater than 600px?

Thanks.

**Comment by ughoo** [comment]
It's a very sad thing, that Samsung made changes in Android core, so they modify the original behaviors in Note series, that set limits to the CSS, also sometimes ignore width values, that lead to everything aligned to the left.
