### ISSUE TITLE
Enable superscipt in text

### ISSUE THREAD

**Issue by rolficak** [EDMdesigner/email-html-generator-issues#23]
Got this feedback from a prospect and wanted to figure out why don't we support superscripts. 

Here's the way they do it:

'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<sup style="font-size:60%;line-height:0;vertical-align:5px">1-3</sup></p>'

This is just an example like how we usually do superscripts
You can see how it works

https://litmus.com/checklist/public/aab9cb4

**Comment by rolficak** [comment]
click edit in waffle to see code

**Comment by ughoo** [comment]
we not supports subscript and superscript, because half of the supported clients ignores it, and also it has a serious isue with line-height.... so if we enable, than multi-line texts will distorting on that line, which has the superscript...because its a cheat of normal line-heights....

**Comment by ughoo** [comment]
and here is the multiline version, where all clients fails.. https://litmus.com/pub/d2ae099
