### ISSUE TITLE
Link rendering error

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/email-html-generator-issues#24]
Dear Support,

Project ID: 588b082831abbe7242c61769

We found an issue that the youtube link http://www.youtube.com/watch?v=$cust_1_video_id$ is rendered as http://www.youtube.com/watch?v#36;cust_1_video_id#36; (missing "=" after "v")
![image](https://cloud.githubusercontent.com/assets/5524183/22365096/a82a4a92-e4b0-11e6-86a9-2cf5c0bfbb18.png)

This will highly affect customers to click the wrong link.

Please help fix this issue as soon as possible, thanks.

**Comment by stubendek** [comment]
@smiska - ha szabad, ide jsont kérnék, ha legközelebb beugrasz az adatbázisba.
