### ISSUE TITLE
Maybe: Gmail bug

### ISSUE THREAD

**Issue by rolficak** [EDMdesigner/email-html-generator-issues#25]
One user reported that his email template doesn't show properly on Gmail. It used to show as expected but since today (March 1, 2017) morning it seems to be wrong. 

Attached screenshot and JSON. 
![screenshot_20170301-072521](https://cloud.githubusercontent.com/assets/6140317/23453673/89e7afc0-fe69-11e6-8d7a-326e9d411de6.png)
[58b13709aa5674f975cb7573.json.zip](https://github.com/EDMdesigner/email-html-generator-issues/files/810207/58b13709aa5674f975cb7573.json.zip)

**Comment by rolficak** [comment]
I ran a Litmus test with one of our built in templates and yes, there seems to be an issue. Since boxes lost their width and everything is left aligned. 
https://litmus.com/pub/2b9b362

**Comment by rolficak** [comment]
Apart from "text" difference, there's an additional extra space, and some other formatting around the closing td tag that makes the difference. 

Left code - fresh export
Code on the right - exported code from January 5, 2017.

![screenshot-www diffchecker com 2017-03-01 15-03-29](https://cloud.githubusercontent.com/assets/6140317/23462992/44ee47ea-fe90-11e6-9526-17fe0de1df2b.png)

**Comment by puinenveturi** [comment]
@ughoo @stubendek could you checkt this issue?

**Comment by ughoo** [comment]
I checked the live generator today, and it works on Gmail mobile, as i tested on our devices. There are some issues on Litmus, but they are not up-2-date Gmail apps.
