### ISSUE TITLE
Accented characters error in a text link

### ISSUE THREAD

**Issue by ademirdiniz** [EDMdesigner/email-html-generator-issues#26]
The accented characters are being converted to unknow code. Take a look:

**Original**: https://www.mediapost.com.br/?campanha=Conheça
**EDM**: https://www.mediapost.com.br/?campanha=Conhe#xE7;a

It happens only in text hiperlink. In button or imagem elements it does work well.

**Comment by ademirdiniz** [comment]
@gyulanemeth ?

**Comment by ademirdiniz** [comment]
@rolficak ?

**Comment by ademirdiniz** [comment]
Hi, @smiska.

Do you have news about this issue?

Thanks

**Comment by smiska** [comment]
Hi Ademir,

The new version of ckeditor is under testing, it is really important that it works perfectly. If the new version has a different output, it can mess up the HTML generator in the system. For this reason we can only release the update, when we are certain that it has no unknown characteristics. 

However, according to my testing the link seems to work well with the current ckeditor too. I could reproduce the issue you have before, but usually it does not happen. Can you update me on your OS and browser information and if there is anything specific condition in which you experience it? I'm continuously trying to identify the reproduction steps, but without having solid reproduction steps I can't confirm if the editor update fixes it or not. Any help is much appreciated. Thanks, in advance and sorry for the inconvenience.

**Comment by ademirdiniz** [comment]
Hi, @smiska. Follow some info about this issue:

OS: Debian GNU/Linux 8 (jessie) 64-bit with GNOME Versão 3.14.1
Browser: Google Chrome version 56.0.2924.87 (64-bit)

You can see the error in the follow link:
[https://suporte.mediapost.com.br/mpview.php?ln=DXO5IVWMe152on1abOw5V-dm07kfYYBQOwaU4z2l5eg,](https://suporte.mediapost.com.br/mpview.php?ln=DXO5IVWMe152on1abOw5V-dm07kfYYBQOwaU4z2l5eg,)

[(Error) The first is an text element with a link](http://cl.ecarta.com.br/orbiknl?h=vBVJbkxu8DMNStfRgvd1ELqo9qj14QMX6JSjhF1rObG0a5wQsfWWcxt2ylAeSRndB8OGDEYJA4z23BaXOgZ1tBBzPhN98fqVNwimVbgUmmG_Z42JZ_gcDxcBacP_QO5YqM6a-5MgDeBAyUxPYOj_-V9_HpDIBxI8FkdTE5rrIp0eqrL-KpYPBKTIWLwAQ6LWB7d3BPV8JuZXg0Q9wHAsow,,)
[(Works well) Second is an image element with a link](http://cl.ecarta.com.br/orbiknl?h=nlMm6xVVIa9YLY_2wN1EsUkeqUSz-5teFyK9bIDgjVq0a5wQsfWWcxt2ylAeSRndB8OGDEYJA4z23BaXOgZ1tBBzPhN98fqVNwimVbgUmmG_Z42JZ_gcDxcBacP_QO5YmSy-Dbgi3eaO1QZX30aONpbzyo_vVapunczC6RW0PdYkMFFcyr5RxU74oYqFCJ0ZXKGneZoqgygFukGmzVMEUw,,)
[(Works well) Third is a button element with a link](http://cl.ecarta.com.br/orbiknl?h=nlMm6xVVIa9YLY_2wN1EsUkeqUSz-5teFyK9bIDgjVq0a5wQsfWWcxt2ylAeSRndB8OGDEYJA4z23BaXOgZ1tBBzPhN98fqVNwimVbgUmmG_Z42JZ_gcDxcBacP_QO5YmSy-Dbgi3eaO1QZX30aONpbzyo_vVapunczC6RW0PdYkMFFcyr5RxU74oYqFCJ0ZXKGneZoqgygFukGmzVMEUw,,)

If you need more information, plese, let me know.
