### ISSUE TITLE
Alt characters not showing

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/email-html-generator-issues#30]
Hi, (again)

We encountered a second client this week that cant seem to convert the ► character to HTML from the editor. (and other characters too, apparently)
It is shown in the ediror, but as soon as you send it, it is not shown. Tried it and can confirm (at least in outlook that this is the case)

![char 1](https://user-images.githubusercontent.com/17139637/28117374-777f9dc2-670d-11e7-8878-604573278798.png)
![char 2](https://user-images.githubusercontent.com/17139637/28117386-8322e922-670d-11e7-85fe-c646c6685570.png)

**Comment by smiska** [comment]
Hi,
I [ran a test](https://litmus.com/checklist/emails/public/7f10539) with a template on Litmus, where there are special characters, I can spot a this character showing up in the previews, even on Outlooks. Could you please provide the projectID for a broken project? Thanks.

**Comment by RichardMailcamp** [comment]
Hi...

Sorry to have wasted your time. just found out that is is NOT the case when an example is sent but its the stored HTML from our DB that is the culprit. Apologies for this.

**Comment by RichardMailcamp** [comment]
You can close

**Comment by smiska** [comment]
No problem @RichardMailcamp , I'm happy that it resolved. Thanks for taking the time to get back to us.
