### ISSUE TITLE
html bug in gmail on android mobile

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/email-html-generator-issues#4]
Hi,

The shape of the newsletter changes when opened in gmail on android mobile.
Is there a way how w2e can fix this?

Kind regards,

Silas de Rooy

JSON in ZIP

Screenshot Gmail Android:
![screenshot_2016-02-08-10-46-04](https://cloud.githubusercontent.com/assets/16222817/12883407/2adb8cd2-ce58-11e5-9e58-7e8d5d16415b.png)

Screenshot preview:
![screenshot](https://cloud.githubusercontent.com/assets/16222817/12883418/45864c66-ce58-11e5-9df1-59ed293ff6e5.png)

**Comment by gyulanemeth** [comment]
Yes, the images might be a little bit streched on gmail app, that is why it's not on our compatibility list: http://edmdesigner.com/compatibility
