### ISSUE TITLE
Links sometimes do not work

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/email-html-generator-issues#5]
For some reason some links are not clickable. Please check this newsletter: http://api-a.edmdesigner.com/jsonp/project/preview/56d06673ed791bdb372bf8f3?user=http://www.rvdb-mail.nl/mailcamp/admin/%20-%202&token=cb25948e273dbd57e6b29d926f8140b2
Under ‘NIEUWE  HR VACATURES’ you see ‘Corporate Recruiter’. De URL in the HTML is;
http://www.rvdb.nl/vacature/?Recruitment-Consultant%2FRvdB%2FWEESP%2F10053-02S0004XTP%2F
And should be
http://www.rvdb.nl/vacature/?Recruitment-Consultant/RvdB/WEESP/10053-02S0004XTP/
Can you please fix this?

**Comment by gyulanemeth** [comment]
Thank you for reporting this, we opened a ticket and will fix it in this sprint (which has started a few minutes ago).

**Comment by gyulanemeth** [comment]
It's fixed and deployed.
