### ISSUE TITLE
'Hide on mobile' option doesn't work

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/email-html-generator-issues#6]
I created a message using EDM  composed of 3 box elements. For the middle one I enabled option "Hide on mobile" but when I send it to my mobile I can see it's still visible. 

Samsung Galaxy S5 (SM-G900F)
Android 5.0
It's a default Android email client

**Comment by agnieszkakowalska** [comment]
Hi, we just noticed that hiding on mobile columns from multicolumn element doesn't work as well

**Comment by rolficak** [comment]
Gmail app is the default application on Android 5.0+

We don't support Gmail (nobody does right now), but the good news is that we are working on a hack to fix Gmail app as well (it's still in research/dev phase, so there's no release that for this yet)

**Comment by agnieszkakowalska** [comment]
OK, thank you
