### ISSUE TITLE
problem with multi column

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/email-html-generator-issues#7]
Hi, A client had a problem that i cannot fix. Couple of things with the multi clomn that just dont seem right.  Double images next to eachother or double text boxes are fine, but text and image is a mess. See json and images. Also, the top multi column doesnt adjust properly with a different color. See capture 2

Thanx, Hope you can reply within the coming days,

Richard

[56eab2a9008b1c5d4c3fc4ef (2).zip](https://github.com/EDMdesigner/email-html-generator-issues/files/177975/56eab2a9008b1c5d4c3fc4ef.2.zip)
![capture2](https://cloud.githubusercontent.com/assets/17139637/13847941/f1044150-ec4f-11e5-9ded-6591d5c73e3b.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17139637/13847942/f104e056-ec4f-11e5-94d2-2da6d4507406.JPG)

**Comment by rolficak** [comment]
@RichardMailcamp Please provide more information about the source of the screenshot (email client, device, etc).

This template looks exactly as expected in supported email clients:
https://litmus.com/pub/516ab00

**Comment by RichardMailcamp** [comment]
Hmm.. That is very strange indeed. In outlook (2016, my email client on PC) it looked exactly as the screenshot provided. When looking at your previews I was pretty stunned that it looked the way it did. I changed some things in the template for the client, so he could continue working on it. So there is no big rush, but things like the different color in the top menubar (contactgegevens) he would have liked to be cyan, but we couldnt keep it in that color because it would shift to the left. As for the multicolumn in the middle, we had to change it to two of the same kind (two images, or two text boxes) to keep it aligned properly. I'm confused about what is happening then if in the json provided it looked allright.

Thanx

**Comment by rolficak** [comment]
Hi Richard, we are not working on this one since couldn't even reproduce the issue - still not sure where have you captured this screenshot. The Litmus test shows that everything is working fine.

**Comment by RichardMailcamp** [comment]
Ok,

Then I’ll communicate to the client that it is an unresolvable/reproducable issue. Thanx for the time anyway

https://www.youtube.com/watch?v=KesPK9uiurI

Met vriendelijke groet,
Richard Crombie

[mc_mail_logo]
Bezoekadres
Nieuwe Hemweg 2
1013 BG Amsterdam

Tel.: +31 (0) 20 705 85 00
Support: support@mailcamp.nlmailto:support@mailcamp.nl
E-mail: richard@mailcamp.nlmailto:richard@mailcamp.nl
Web: www.mailcamp.nlhttp://www.mailcamp.nl/

Van: Roland Pokornyik [mailto:notifications@github.com]
Verzonden: Tuesday, March 22, 2016 12:28
Aan: EDMdesigner/email-html-generator-issues email-html-generator-issues@noreply.github.com
CC: Richard Crombie richard@mailcamp.nl
Onderwerp: Re: [email-html-generator-issues] problem with multi column (#7)

Hi Richard, we are not working on this one since couldn't even reproduce the issue - still not sure where have you captured this screenshot. The Litmus test shows that everything is working fine.
