### ISSUE TITLE
Images not showing in Outlook 2007

### ISSUE THREAD

**Issue by witoldlitwin** [EDMdesigner/email-html-generator-issues#8]
Hi, one of our clients claims that message images don't show in Outlook 2007 and earlier. Could you check that? Problematic message id is 56f2c6d6ed6112df7127d7ef. Please ignore wrong (relative) URL of logo image - problem is with ALL images.

**Comment by gyulanemeth** [comment]
Thank you for reporting this, we will investigate it asap.

**Comment by witoldlitwin** [comment]
Thanks! An update from the client: "images don't work with the links that EDM is generating but if we use the same images uploaded externally - it works"

**Comment by gyulanemeth** [comment]
Hello,

can you please attach example jsons to this issue, so we can investigate?

**Comment by agnieszkakowalska** [comment]
Hi Gyula, can you find it by id 56f2c6d6ed6112df7127d7ef ?

**Comment by gyulanemeth** [comment]
Hello, I was trying to find the project, but I could not find any projects with this id.

**Comment by smiska** [comment]
Hi @witoldlitwin @agnieszkakowalska ,

I just want to check the current status of this issue.
Please drop a line if this needs any follow up, or can be closed!

Thanks!

**Comment by agnieszkakowalska** [comment]
Hi @smiska, please close this issue.
